version: '3'

networks:
  uploader:

services:

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ${PWD}/src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - uploader

  composer:
    image: composer
    volumes:
      - ${PWD}/src:/var/www/html
    working_dir: /var/www/html
    command: bash -c "composer install --no-interaction"

  php:
    build:
      context: ./php-fpm
    volumes:
      - ${PWD}/src:/var/www/html
    ports:
      - "9000:9000"

    networks:
      - uploader
