version: '3'

networks:
  uploader:

services:

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ${PWD}/src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db
    networks:
      - uploader

  php:
    build:
      context: ./php-fpm
    volumes:
      - ${PWD}/src:/var/www/html
    ports:
      - "9000:9000"

    networks:
      - uploader
