version: '3'

networks:
  uploader:

services:

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ${PWD}/..:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php_campaigns-sync
      - postgres_campaigns-sync
    networks:
      - uploader

  db:
    image: postgres:14.2-alpine
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=uploader
      - POSTGRES_USER=uploader_admin
      - POSTGRES_PASSWORD=12qwaszx
    networks:
      - uploader

  php:
    build:
      context: ./php-fpm
    volumes:
      - ${PWD}/src:/var/www/html
    ports:
      - "9000:9000"

    networks:
      - uploader
