version: '3'

networks:
  uploader:

services:

  php:
    build:
      context: ./php-fpm
    volumes:
      - ${PWD}/src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - uploader

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ${PWD}/src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - uploader
    depends_on:
      - php

  install-dependencies:
    build:
      context: ./dependencies
    volumes:
      - ${PWD}/src:/var/www/html
    command: bash -c "composer install --no-interaction && php artisan storage:link --force"
    depends_on:
      - php
